# Generated by Django 4.0.1 on 2022-01-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_post_author_delete_author_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.TextField(default='', max_length=500),
        ),
    ]
